#!/usr/bin/env bash
# run_v4_temporal_query_wm_train_only.sh — Phase 1 v4 TemporalDynamicQueryResidualWM train launcher.
#
# Train sweep over v4 architecture variants (stage, history length, query count):
#   bash scripts/libero/phase1/run_v4_temporal_query_wm_train_only.sh spatial
#
# Sweep mode (multiple configs, one by one):
#   SWEEP=1 SWEEP_PRESET=stage_only RUN_NAME=v4_sweep_$(date +%Y%m%d) \
#     bash scripts/libero/phase1/run_v4_temporal_query_wm_train_only.sh spatial
#
# Single-config quick run (just v4b defaults):
#   SWEEP=0 EXP_NAME=v4b bash scripts/libero/phase1/run_v4_temporal_query_wm_train_only.sh spatial
#
# Multi-node split:
#   Node 0: NUM_NODES=2 NODE_INDEX=0 SWEEP=1 SWEEP_PRESET=full RUN_NAME=v4_sweep ...
#   Node 1: NUM_NODES=2 NODE_INDEX=1 SWEEP=1 SWEEP_PRESET=full RUN_NAME=v4_sweep ...
#
# Useful overrides:
#   SWEEP_PRESET=stage_only | history | queries | lambda | quick | full
#   MAX_STEPS=150000 HISTORY_LENGTH=2 NUM_DYNAMIC_QUERIES=8
#   LAMBDA_RANK=1.0 LAMBDA_QUERY=0.5
#   USE_ACTION_FUTURE_SCORER=1  (0=v4a, 1=v4b)
#   WORLD_MODEL_BATCH_SIZE=16 BATCH_SIZE=1
#   DRY_RUN=1

set -euo pipefail

SCRIPT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
REPO_ROOT=$(cd "${SCRIPT_DIR}/../../.." && pwd)
WM_SCRIPTS="${SCRIPT_DIR}/../residual_worldmodel"

source "${WM_SCRIPTS}/common.sh"

is_true() { case "${1:-}" in 1|true|TRUE|True|yes|YES) return 0 ;; *) return 1 ;; esac; }
log() { echo "[phase1-v4-train] $(date +%H:%M:%S) $*"; }

TASK_SUITE="${1:-${TASK_SUITE:-spatial}}"
SWEEP="${SWEEP:-0}"

if ! is_true "${SWEEP}"; then
  # Single run — pass through directly to backend train script
  exec bash "${WM_SCRIPTS}/train_v4_temporal_query_worldmodel.sh" "${TASK_SUITE}"
fi

# ---------------------------------------------------------------------------
# Sweep mode
# ---------------------------------------------------------------------------
SWEEP_PRESET="${SWEEP_PRESET:-stage_only}"
DATE_TAG=$(timestamp)
RUN_NAME="${RUN_NAME:-v4_${DATE_TAG}_${TASK_SUITE}_${SWEEP_PRESET}}"
SEED="${SEED:-42}"
NUM_NODES="${NUM_NODES:-${NUM_PCS:-${SHARD_COUNT:-1}}}"
NODE_INDEX="${NODE_INDEX:-${PC_INDEX:-${SHARD_INDEX:-0}}}"
GPU_IDS="${GPU_IDS:-auto}"
DRY_RUN="${DRY_RUN:-0}"
STOP_ON_FAIL="${STOP_ON_FAIL:-0}"

CKPT_ROOT="${CKPT_ROOT:-${REPO_ROOT}/checkpoints/libero/TemporalQueryResidualWM/phase1_sweeps/${RUN_NAME}}"
OUT_ROOT="${OUT_ROOT:-${REPO_ROOT}/results/phase1/v4_sweeps/${RUN_NAME}}"
LOG_ROOT="${LOG_ROOT:-${OUT_ROOT}/logs/node${NODE_INDEX}_of_${NUM_NODES}}"

mkdir -p "${OUT_ROOT}" "${LOG_ROOT}"
printf '%s\n' "${OUT_ROOT}" > "${REPO_ROOT}/results/phase1/latest.txt"

log "=== Phase 1 v4 train sweep ==="
log "task_suite  : ${TASK_SUITE}"
log "preset      : ${SWEEP_PRESET}"
log "run_name    : ${RUN_NAME}"
log "node shard  : ${NODE_INDEX}/${NUM_NODES}"
log "ckpt_root   : ${CKPT_ROOT}"
log "out_root    : ${OUT_ROOT}"

SWEEP=0 \
NUM_NODES="${NUM_NODES}" \
NODE_INDEX="${NODE_INDEX}" \
GPU_IDS="${GPU_IDS}" \
DRY_RUN="${DRY_RUN}" \
STOP_ON_FAIL="${STOP_ON_FAIL}" \
SWEEP_PRESET="${SWEEP_PRESET}" \
RUN_NAME="${RUN_NAME}" \
SEED="${SEED}" \
CKPT_ROOT="${CKPT_ROOT}" \
OUT_ROOT="${OUT_ROOT}" \
LOG_ROOT="${LOG_ROOT}" \
  bash "${WM_SCRIPTS}/run_v4_temporal_query_ablation.sh" "${TASK_SUITE}"

log "=== v4 train sweep complete ==="
log "ckpts   : ${CKPT_ROOT}"
log "results : ${OUT_ROOT}"
echo ""
echo "  To evaluate, run:"
echo "    bash scripts/libero/phase1/run_v4_temporal_query_wm_eval_only.sh ${TASK_SUITE}"
echo ""
echo "  To run eval command list generated by ablation:"
echo "    bash ${OUT_ROOT}/eval_commands.sh"
